markdown: kramdown 
highlighter: rouge
kramdown:
  input: GFM
  default_lang: javascript 
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
